### ISSUE TITLE
Relax dependency on cryptonite

### ISSUE THREAD

**Issue by kaol** [sarthakbagaria/web-push#2]
cryptonite strives to keep a stable API and new versions mainly just add new modules to it. web-push has a dependency on a set version of the library and this makes installing it with cabal difficult. Could you please consider using just a lower limit for it?

**Comment by yaitskov** [comment]
I would decouple from Lens too

**Comment by sarthakbagaria** [comment]
Sounds reasonable. Removed upper bounds from these libraries in bac32942ce4b0c1e88142f9494539b78f37b9f36.

**Comment by kaol** [comment]
Thanks. May I suggest a revision on Hackage with the relaxed dependencies, if you're not planning on making a release yet.

**Comment by sarthakbagaria** [comment]
I have just tested and packaged the latest commit and uploaded on Hackage. Please check [here](https://hackage.haskell.org/package/web-push-0.3).
