### ISSUE TITLE
Need standard VAPID key loader 

### ISSUE THREAD

**Issue by yaitskov** [sarthakbagaria/web-push#3]
All WebPush libraries, I used before, are representing keys as 2 base64 numbers (private and public).
Java library generates/accepts in such format and [online generator](https://d3v.one/vapid-key-generator/).

```
private
JgAbzB_Ke_Y81q81NaPkXeblC888bTBFih2G-bEzhD8
public BFR1zzv0wz5nL0BhlrZBMKFpSlZfvph7_IpjqO8nbT5gs18OMJ0K97o2ITGV5-8xTmRlLLU4hKsSbydgah19gQw
```

VAPIDKeysMinDetails has 3 fields!

```
-- |3 integers minimally representing a unique VAPID key pair.
data VAPIDKeysMinDetails = VAPIDKeysMinDetails { privateNumber :: Integer
                                               , publicCoordX :: Integer
                                               , publicCoordY :: Integer
                                               } deriving (Show)
```

Should I split a public key in 2 halves to populate publicCoordX and publicCoordY?

**Comment by sarthakbagaria** [comment]
You are probably looking for something like [this](https://stackoverflow.com/questions/30116758/generating-publickey-from-x-and-y-values-of-elliptic-curve-point).
