### ISSUE TITLE
Sync with Jose rename   createJWSJWT -> signClaims

### ISSUE THREAD

**Issue by yaitskov** [sarthakbagaria/web-push#4]
https://github.com/frasertweedale/hs-jose/commit/4acece620b36fd97b1ff82ed07e16b035f81234e

I am trying to build the lib with ghc 8.8.3 and run into issues with memory exception and jose libraries.

I enforced new version and reached stage where web-push is building.
Jose 0.8.3 contains renamed functions, older versions are not buildable.

**Comment by sarthakbagaria** [comment]
Current latest version of the library is only tested to run against [Stack LTS 13.0](https://www.stackage.org/lts-13.0). I will upgrade to a more recent LTS version soon. You may submit a pull request if you have done that already.

**Comment by yaitskov** [comment]
I noticed that Jose is already removed in the trunk, but not published on hackage.

I figured out at last how to depend on libraries just from github in stack.
I updated lts [version up to 15.10](https://github.com/yaitskov/web-push/tree/lts-15.10).
[In the demo app](https://github.com/yaitskov/web-push-with-elm-haskell) on attempt to publish message to endpoint the following exception happens.
I tried to upgrade binary version but it behaves the same (Firefox and Chrome endpoints)
I noticed it is really hard to find what encoding should be used for p256dh and auth fields.
I was using Hex encoding and there was any error! and Firefox even was receiving something complaining in console log that she cannot decode message.

I was not able to find runGet reference in web-push codebase.
 

```
 wp-server &
[1] 23368
09:55$ wwd is on port 8080...

09:55$ Data.Binary.Get.runGet at position 56: not enough bytes
CallStack (from HasCallStack):
  error, called at src/Data/Binary/Get.hs:351:5 in binary-0.8.8.0-9Lj2FGv7OWf9UbYRbk4cc:Data.Binary.Get
```

**Comment by sarthakbagaria** [comment]
I have now added a demo app in the commit c4d04a04a5f3bf123f9b1ef5e87ff087db07a630. You can refer to that to see how to set those fields. I have put instructions in the readme on how to run the demo app. I have also created a [new revision](https://hackage.haskell.org/package/web-push-0.3) on Hackage from this commit.
